#!/bin/bash
# Regenerate src/sigstore_trust_embedded.erl from the Sigstore root-signing
# repositories (SPEC.md §2a V4). The output is checked in so vendoring is a
# plain file copy. Run from the repo root; review the diff before committing.
#
# NOTE: these are fetched from GitHub over TLS, NOT through TUF. They are an
# offline bootstrap snapshot until the TUF client lands (M6).
set -euo pipefail
out=src/sigstore_trust_embedded.erl
prod=https://raw.githubusercontent.com/sigstore/root-signing/main/targets
stag=https://raw.githubusercontent.com/sigstore/root-signing-staging/main/targets
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
curl -sSfL -o "$tmp/prod_tr.json" "$prod/trusted_root.json"
curl -sSfL -o "$tmp/prod_sc.json" "$prod/signing_config.v0.2.json"
curl -sSfL -o "$tmp/stag_tr.json" "$stag/trusted_root.json"
curl -sSfL -o "$tmp/stag_sc.json" "$stag/signing_config.v0.2.json"

lit() { # JSON file -> Erlang binary literal (escape \ and ")
  printf '<<"'; sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' "$1" | awk 'BEGIN{ORS="\\n"}{print}'; printf '"/utf8>>'
}
sha() { shasum -a 256 "$1" | cut -d' ' -f1; }

{
  echo "%% GENERATED by scripts/embed_trust_roots.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit."
  echo "%%"
  echo "%% Offline bootstrap snapshot of Sigstore trust material, fetched over"
  echo "%% TLS from GitHub (not via TUF; see SPEC.md §8.1). Sources and SHA-256:"
  echo "%%   production trusted_root.json         $(sha "$tmp/prod_tr.json")"
  echo "%%     $prod/trusted_root.json"
  echo "%%   production signing_config.v0.2.json  $(sha "$tmp/prod_sc.json")"
  echo "%%     $prod/signing_config.v0.2.json"
  echo "%%   staging trusted_root.json            $(sha "$tmp/stag_tr.json")"
  echo "%%     $stag/trusted_root.json"
  echo "%%   staging signing_config.v0.2.json     $(sha "$tmp/stag_sc.json")"
  echo "%%     $stag/signing_config.v0.2.json"
  echo "-module(sigstore_trust_embedded)."
  echo
  echo "-export([trusted_root/1, signing_config/1])."
  echo
  echo "-spec trusted_root(production | staging) -> binary()."
  echo "trusted_root(production) ->"; echo "    $(lit "$tmp/prod_tr.json");"
  echo "trusted_root(staging) ->"; echo "    $(lit "$tmp/stag_tr.json")."
  echo
  echo "-spec signing_config(production | staging) -> binary()."
  echo "signing_config(production) ->"; echo "    $(lit "$tmp/prod_sc.json");"
  echo "signing_config(staging) ->"; echo "    $(lit "$tmp/stag_sc.json")."
} > "$out"
echo "wrote $out"
